service: sls-telegram-bot
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    stage: prod
    region: eu-west-1

functions:
    hook:
        handler: bot.handler
        events:
            - http:
                  path: /
                  method: post
                  cors: true

package:
    include:
        - locales/**

plugins:
    - serverless-esbuild
